# Generated by Django 4.1.3 on 2022-11-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_hashtag_view_hashtag_rename_post_view_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(related_name='posts', to='posts.hashtag'),
        ),
    ]
